### ISSUE TITLE
Dontpad pages are not loading

### ISSUE THREAD

**Issue by micaelviana** [huynhsamha/dontpad#18]
When I try to enter some link this message appears:

---
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
`Heroku logs --tail`
---

I can no longer access my texts. This happens for any link

**Comment by huynhsamha** [comment]
Recently Heroku has stopped providing free deployment, and I don't have time to maintain this project anymore.

If you need to retrieve the information that you have saved on https://dontpad.herokuapp.com/, you can contact me via email [huynhha12798@gmail.com](mailto:huynhha12798@gmail.com) with subject "[dontpad] ...", I will resend that content from the database.

Sorry for the inconvenience.
